#!/usr/bin/env bash
# drive_suma_render.sh
# --------------------
# OPTIONAL fallback: drive SUMA via Xvfb to take an anterior-view screenshot,
# reproducing the manual "open in SUMA / rotate brain / snapshot" workflow.
#
# Most users won't need this — `run_make_figures.sh` already produces an
# anterior-view PNG with nilearn, no X server required. This script exists for
# the case where you want the SUMA-rendered look exactly.
#
# Usage:
#   ./drive_suma_render.sh <surface_spec.spec> <overlay.nii> <out.png>
#
# `surface_spec.spec` is a SUMA spec file pointing at a cortical surface
# (e.g. fsaverage or your own). It is not auto-generated by this script;
# create one once with @SUMA_Make_Spec_FS / @SUMA_Make_Spec_SF.

set -euo pipefail

if [[ $# -lt 3 ]]; then
    echo "Usage: $0 <surface.spec> <overlay.nii> <out.png>" >&2
    exit 2
fi
SPEC="$(realpath "$1")"
OVERLAY="$(realpath "$2")"
OUT_PNG="$(realpath -m "$3")"
SPEC_DIR="$(dirname "$SPEC")"
SURFVOL="$SPEC_DIR/MNI_N27_SurfVol.nii"

# Ensure AFNI/SUMA on PATH.
if ! command -v suma >/dev/null 2>&1; then
    if [[ -x "$HOME/abin/suma" ]]; then
        export PATH="$HOME/abin:$PATH"
    else
        echo "ERROR: suma not on PATH and \$HOME/abin/suma not found." >&2
        exit 1
    fi
fi
if ! command -v afni >/dev/null 2>&1; then
    if [[ -x "$HOME/abin/afni" ]]; then
        export PATH="$HOME/abin:$PATH"
    else
        echo "ERROR: afni not on PATH and \$HOME/abin/afni not found." >&2
        exit 1
    fi
fi
if ! command -v plugout_drive >/dev/null 2>&1; then
    echo "ERROR: plugout_drive not on PATH." >&2
    exit 1
fi
if ! command -v 3dVol2Surf >/dev/null 2>&1; then
    echo "ERROR: 3dVol2Surf not on PATH." >&2
    exit 1
fi

# Headless X via Xvfb.
if ! command -v Xvfb >/dev/null 2>&1; then
    echo "ERROR: Xvfb not installed. apt install xvfb" >&2
    exit 1
fi

DISPLAY_NUM="${SUMA_DISPLAY:-:99}"
PORT_BLOCK="${SUMA_NPB:-0}"
SURFACE_LABELS="${SUMA_SURFACE_LABELS:-lh.pial.gii rh.pial.gii}"
VIEW_KEYS="${SUMA_VIEW_KEYS:-ctrl+left right right right right right right right right right right right right right right right right right right}"
SNAP_DIR="$(mktemp -d)"
trap 'rm -rf "$SNAP_DIR"' EXIT

Xvfb "$DISPLAY_NUM" -screen 0 1280x1024x24 >/dev/null 2>&1 &
XVFB_PID=$!
trap 'kill "$XVFB_PID" 2>/dev/null || true; rm -rf "$SNAP_DIR"' EXIT
export DISPLAY="$DISPLAY_NUM"
sleep 1

# Start AFNI and SUMA in the background, then drive them.
cd "$SNAP_DIR"
LH_SPEC="$SPEC_DIR/MNI_N27_lh.spec"
RH_SPEC="$SPEC_DIR/MNI_N27_rh.spec"
LH_DSET="$SNAP_DIR/lh_overlay.niml.dset"
RH_DSET="$SNAP_DIR/rh_overlay.niml.dset"
if [[ -f "$SURFVOL" && -f "$LH_SPEC" && -f "$RH_SPEC" ]]; then
    3dVol2Surf \
        -spec "$LH_SPEC" \
        -surf_A lh.smoothwm \
        -surf_B lh.pial \
        -sv "$SURFVOL" \
        -grid_parent "$OVERLAY" \
        -map_func max_abs \
        -f_steps 10 \
        -f_index nodes \
        -oob_value 0 \
        -out_niml "$LH_DSET" >/dev/null
    3dVol2Surf \
        -spec "$RH_SPEC" \
        -surf_A rh.smoothwm \
        -surf_B rh.pial \
        -sv "$SURFVOL" \
        -grid_parent "$OVERLAY" \
        -map_func max_abs \
        -f_steps 10 \
        -f_index nodes \
        -oob_value 0 \
        -out_niml "$RH_DSET" >/dev/null
else
    echo "ERROR: expected MNI_N27 SurfVol and hemisphere specs next to $SPEC." >&2
    exit 1
fi

afni -q -npb "$PORT_BLOCK" -niml -yesplugouts "$SPEC_DIR" "$(dirname "$OVERLAY")" >/dev/null 2>&1 &
AFNI_PID=$!
trap 'kill "$AFNI_PID" "$XVFB_PID" 2>/dev/null || true; rm -rf "$SNAP_DIR"' EXIT
sleep 2

if [[ -f "$SURFVOL" ]]; then
    suma -npb "$PORT_BLOCK" -spec "$SPEC" -sv "$SURFVOL" -niml >/dev/null 2>&1 &
else
    suma -npb "$PORT_BLOCK" -spec "$SPEC" -niml >/dev/null 2>&1 &
fi
SUMA_PID=$!
trap 'kill "$SUMA_PID" "$AFNI_PID" "$XVFB_PID" 2>/dev/null || true; rm -rf "$SNAP_DIR"' EXIT
sleep 3

# Load the overlay in AFNI and make AFNI/SUMA talk.
plugout_drive -npb "$PORT_BLOCK" \
    -com "SWITCH_UNDERLAY MNI_N27_SurfVol.nii" \
    -com "SWITCH_OVERLAY $(basename "$OVERLAY")" \
    -com "SEE_OVERLAY +" \
    -quit
for surface_label in $SURFACE_LABELS; do
    DriveSuma -npb "$PORT_BLOCK" -com surf_cont \
        -switch_surf "$surface_label" \
        -view_surf y
done
DriveSuma -npb "$PORT_BLOCK" -com surf_cont \
    -load_dset "$LH_DSET" \
    -surf_label lh.pial.gii \
    -I_sb 0 \
    -I_range 3 \
    -T_sb -1 \
    -Dsp Col \
    -view_dset y
for surface_label in $SURFACE_LABELS; do
    DriveSuma -npb "$PORT_BLOCK" -com surf_cont \
        -switch_surf "$surface_label" \
        -view_surf y
done
DriveSuma -npb "$PORT_BLOCK" -com surf_cont \
    -load_dset "$RH_DSET" \
    -surf_label rh.pial.gii \
    -I_sb 0 \
    -I_range 3 \
    -T_sb -1 \
    -Dsp Col \
    -view_dset y
DriveSuma -npb "$PORT_BLOCK" -com viewer_cont -viewer_position 0 0 -viewer_size 1024 1024
view_args=( -npb "$PORT_BLOCK" -com viewer_cont )
for key in $VIEW_KEYS; do
    view_args+=( -key "$key" )
done
DriveSuma "${view_args[@]}"
sleep 1
DriveSuma -npb "$PORT_BLOCK" -com viewer_cont \
    -autorecord "$SNAP_DIR/suma_record.ppm" \
    -key "ctrl+r"
sleep 1
DriveSuma -npb "$PORT_BLOCK" -com kill_suma
plugout_drive -npb "$PORT_BLOCK" -com "QUIT" -quit >/dev/null 2>&1 || true

# SUMA can either write the autorecord PPM or numbered snapshots.
shopt -s nullglob
shots=( "$SNAP_DIR"/suma_record*.ppm "$SNAP_DIR"/SUMA_*.jpg "$SNAP_DIR"/SUMA_*.png )
if (( ${#shots[@]} )); then
    mkdir -p "$(dirname "$OUT_PNG")"
    case "${shots[0]}" in
        *.ppm)
            if command -v convert >/dev/null 2>&1; then
                convert "${shots[0]}" "$OUT_PNG"
            elif command -v pnmtopng >/dev/null 2>&1; then
                pnmtopng "${shots[0]}" > "$OUT_PNG"
            else
                echo "ERROR: SUMA wrote PPM but neither convert nor pnmtopng is available." >&2
                exit 1
            fi
            ;;
        *)
            mv "${shots[0]}" "$OUT_PNG"
            ;;
    esac
    rm -f "${shots[@]:1}"
    echo "Wrote $OUT_PNG"
else
    echo "ERROR: no SUMA snapshot produced. Check DriveSuma recorder commands." >&2
    exit 1
fi
